#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh"

sketchybar --bar height=27 \
	color="$TRANSPARENT" \
	shadow="$SHADOW" \
	position=top \
	y_offset=0 \
	padding_right=11 \
	padding_left=10 \
	blur_radius=0 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:13.5" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Bold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
    # corner_radius="$CORNER_RADIUS" \
	# sticky=on \
	# margin=5 \

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

source "$ITEM_DIR/calendar.sh"

source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"

sketchybar --hotload true

sketchybar --update

echo "sketchybar configuration loaded.."
